#############################################################################
# Makefile for building: simpleMainwindow
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Jul 7 16:54:37 2015
# Project:  simpleMainwindow.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile simpleMainwindow.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DGL_GLEXT_PROTOTYPES -DQT_NO_DEBUG -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -frounding-math -std=c++0x -fopenmp -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/include/qt3/ -I/usr/include/qt4/QtXml -Iinclude -Ilib/libigl/include -Ilib/eigen/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/X11R6/lib64 -lQtOpenGL -lQGLViewer -lglut -lGL -lGLU -lOpenMeshCore -lOpenMeshTools -lgomp -lQt3Support -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/GLViewer.cpp \
		src/MainWidow.cpp \
		src/Mesh.cpp \
		src/Shader.cpp \
		src/ToothSegmentation.cpp moc_GLViewer.cpp \
		moc_MainWindow.cpp
OBJECTS       = main.o \
		GLViewer.o \
		MainWidow.o \
		Mesh.o \
		Shader.o \
		ToothSegmentation.o \
		moc_GLViewer.o \
		moc_MainWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		simpleMainwindow.pro
QMAKE_TARGET  = simpleMainwindow
DESTDIR       = 
TARGET        = simpleMainwindow

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: simpleMainwindow.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtOpenGL.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl \
		/usr/lib/i386-linux-gnu/libQt3Support.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile simpleMainwindow.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtOpenGL.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
/usr/lib/i386-linux-gnu/libQt3Support.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile simpleMainwindow.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/simpleMainwindow1.0.0 || $(MKDIR) .tmp/simpleMainwindow1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/simpleMainwindow1.0.0/ && $(COPY_FILE) --parents include/BoundingBox.h include/GLViewer.h include/MainWindow.h include/Mesh.h include/Shader.h include/ToothSegmentation.h .tmp/simpleMainwindow1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/GLViewer.cpp src/MainWidow.cpp src/Mesh.cpp src/Shader.cpp src/ToothSegmentation.cpp .tmp/simpleMainwindow1.0.0/ && $(COPY_FILE) --parents ui_templates/mainwindow.ui .tmp/simpleMainwindow1.0.0/ && (cd `dirname .tmp/simpleMainwindow1.0.0` && $(TAR) simpleMainwindow1.0.0.tar simpleMainwindow1.0.0 && $(COMPRESS) simpleMainwindow1.0.0.tar) && $(MOVE) `dirname .tmp/simpleMainwindow1.0.0`/simpleMainwindow1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/simpleMainwindow1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_GLViewer.cpp moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GLViewer.cpp moc_MainWindow.cpp
moc_GLViewer.cpp: include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h \
		include/GLViewer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/GLViewer.h -o moc_GLViewer.cpp

moc_MainWindow.cpp: include/GLViewer.h \
		include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h \
		ui_mainwindow.h \
		include/MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/MainWindow.h -o moc_MainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ui_templates/mainwindow.ui \
		include/GLViewer.h \
		include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h
	/usr/bin/uic-qt4 ui_templates/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp include/MainWindow.h \
		include/GLViewer.h \
		include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

GLViewer.o: src/GLViewer.cpp include/GLViewer.h \
		include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLViewer.o src/GLViewer.cpp

MainWidow.o: src/MainWidow.cpp include/MainWindow.h \
		include/GLViewer.h \
		include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWidow.o src/MainWidow.cpp

Mesh.o: src/Mesh.cpp include/Mesh.h \
		include/BoundingBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mesh.o src/Mesh.cpp

Shader.o: src/Shader.cpp include/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Shader.o src/Shader.cpp

ToothSegmentation.o: src/ToothSegmentation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ToothSegmentation.o src/ToothSegmentation.cpp

moc_GLViewer.o: moc_GLViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GLViewer.o moc_GLViewer.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

