#############################################################################
# Makefile for building: simpleMainwindow
# Generated by qmake (2.01a) (Qt 4.8.1) on: ?? 8? 31 20:07:41 2015
# Project:  simpleMainwindow.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile simpleMainwindow.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DGL_GLEXT_PROTOTYPES -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -frounding-math -std=c++0x -fopenmp -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/include/qt3/ -I/usr/include/qt4/QtXml -Iinclude -Ilib/libigl/include -Ilib/eigen/include -I/usr/include/pcl-1.7 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/X11R6/lib64 -lQtOpenGL -lQGLViewer -lglut -lGL -lGLU -lOpenMeshCore -lOpenMeshTools -lgomp -lgsl -lgslcblas -lpcl_kdtree -lQt3Support -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/GLViewer.cpp \
		src/MainWidow.cpp \
		src/Mesh.cpp \
		src/Shader.cpp \
		src/ToothSegmentation.cpp \
		src/CurvatureComputer.cpp moc_GLViewer.cpp \
		moc_MainWindow.cpp \
		moc_ToothSegmentation.cpp \
		moc_CurvatureComputer.cpp \
		qrc_ToothSegmentation.cpp
OBJECTS       = main.o \
		GLViewer.o \
		MainWidow.o \
		Mesh.o \
		Shader.o \
		ToothSegmentation.o \
		CurvatureComputer.o \
		moc_GLViewer.o \
		moc_MainWindow.o \
		moc_ToothSegmentation.o \
		moc_CurvatureComputer.o \
		qrc_ToothSegmentation.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		simpleMainwindow.pro
QMAKE_TARGET  = simpleMainwindow
DESTDIR       = 
TARGET        = simpleMainwindow

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: simpleMainwindow.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtOpenGL.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl \
		/usr/lib/i386-linux-gnu/libQt3Support.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile simpleMainwindow.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtOpenGL.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
/usr/lib/i386-linux-gnu/libQt3Support.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile simpleMainwindow.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/simpleMainwindow1.0.0 || $(MKDIR) .tmp/simpleMainwindow1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/simpleMainwindow1.0.0/ && $(COPY_FILE) --parents include/BoundingBox.h include/GLViewer.h include/MainWindow.h include/Mesh.h include/Shader.h include/ToothSegmentation.h include/CurvatureComputer.h .tmp/simpleMainwindow1.0.0/ && $(COPY_FILE) --parents resource/ToothSegmentation.qrc .tmp/simpleMainwindow1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/GLViewer.cpp src/MainWidow.cpp src/Mesh.cpp src/Shader.cpp src/ToothSegmentation.cpp src/CurvatureComputer.cpp .tmp/simpleMainwindow1.0.0/ && $(COPY_FILE) --parents ui_templates/mainwindow.ui .tmp/simpleMainwindow1.0.0/ && (cd `dirname .tmp/simpleMainwindow1.0.0` && $(TAR) simpleMainwindow1.0.0.tar simpleMainwindow1.0.0 && $(COMPRESS) simpleMainwindow1.0.0.tar) && $(MOVE) `dirname .tmp/simpleMainwindow1.0.0`/simpleMainwindow1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/simpleMainwindow1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_GLViewer.cpp moc_MainWindow.cpp moc_ToothSegmentation.cpp moc_CurvatureComputer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GLViewer.cpp moc_MainWindow.cpp moc_ToothSegmentation.cpp moc_CurvatureComputer.cpp
moc_GLViewer.cpp: include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h \
		include/GLViewer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/GLViewer.h -o moc_GLViewer.cpp

moc_MainWindow.cpp: include/GLViewer.h \
		include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h \
		ui_mainwindow.h \
		include/ToothSegmentation.h \
		include/MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/MainWindow.h -o moc_MainWindow.cpp

moc_ToothSegmentation.cpp: include/Mesh.h \
		include/BoundingBox.h \
		include/ToothSegmentation.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/ToothSegmentation.h -o moc_ToothSegmentation.cpp

moc_CurvatureComputer.cpp: include/Mesh.h \
		include/BoundingBox.h \
		include/CurvatureComputer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/CurvatureComputer.h -o moc_CurvatureComputer.cpp

compiler_rcc_make_all: qrc_ToothSegmentation.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ToothSegmentation.cpp
qrc_ToothSegmentation.cpp: resource/ToothSegmentation.qrc \
		resource/image/toolbar_enable_manual_operation_checked.png \
		resource/image/toolbar_program_control_pause.png \
		resource/image/toolbar_enable_manual_operation_normal.png \
		resource/image/toolbar_delete_error_contour_section.png \
		resource/image/toolbar_add_boundary_vertex.png \
		resource/image/toolbar_flip_cutting_plane.png \
		resource/image/toolbar_move_cutting_plane_up.png \
		resource/image/toolbar_move_cutting_plane_down.png \
		resource/image/toolbar_delete_boundary_vertex.png \
		resource/image/toolbar_show_vertex_properties.png \
		resource/image/toolbar_program_control_start.png \
		resource/image/toolbar_delete_error_tooth_region.png
	/usr/bin/rcc -name ToothSegmentation resource/ToothSegmentation.qrc -o qrc_ToothSegmentation.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ui_templates/mainwindow.ui \
		include/GLViewer.h \
		include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h
	/usr/bin/uic-qt4 ui_templates/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp include/MainWindow.h \
		include/GLViewer.h \
		include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h \
		ui_mainwindow.h \
		include/ToothSegmentation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

GLViewer.o: src/GLViewer.cpp include/Mesh.h \
		include/BoundingBox.h \
		include/GLViewer.h \
		include/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLViewer.o src/GLViewer.cpp

MainWidow.o: src/MainWidow.cpp include/MainWindow.h \
		include/GLViewer.h \
		include/Mesh.h \
		include/BoundingBox.h \
		include/Shader.h \
		ui_mainwindow.h \
		include/ToothSegmentation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWidow.o src/MainWidow.cpp

Mesh.o: src/Mesh.cpp include/Mesh.h \
		include/BoundingBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mesh.o src/Mesh.cpp

Shader.o: src/Shader.cpp include/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Shader.o src/Shader.cpp

ToothSegmentation.o: src/ToothSegmentation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ToothSegmentation.o src/ToothSegmentation.cpp

CurvatureComputer.o: src/CurvatureComputer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CurvatureComputer.o src/CurvatureComputer.cpp

moc_GLViewer.o: moc_GLViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GLViewer.o moc_GLViewer.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_ToothSegmentation.o: moc_ToothSegmentation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ToothSegmentation.o moc_ToothSegmentation.cpp

moc_CurvatureComputer.o: moc_CurvatureComputer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CurvatureComputer.o moc_CurvatureComputer.cpp

qrc_ToothSegmentation.o: qrc_ToothSegmentation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ToothSegmentation.o qrc_ToothSegmentation.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

